### ISSUE TITLE
outdated python.dll on latest blender.

### ISSUE THREAD

**Issue by A-Lamia** [Nicolas-Constanty/AutoRemesher-Blender#6]
Hey, newer versions of blender 2.93 and 2.92 are using python3.9 is there going to be an update for this ?

**Comment by Nicolas-Constanty** [comment]
Hello @A-Lamia , yes sure I will had support for this probably in the next days. 
Rigth now I'm finishing to implement the Continious Integration for the Linux version of the Addon.

**Comment by A-Lamia** [comment]
@Nicolas-Constanty , Awesome! Thanks for the hard work.

**Comment by Nicolas-Constanty** [comment]
Support for Blender 2.93 with python 3.9 has been added. You can download it [in the release page](https://github.com/Nicolas-Constanty/AutoRemesher-Blender/releases). 
If it's working for you, I will close this issue.
